// <auto-generated />
using System;
using AdvancedWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdvancedWebApi.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdvancedWebApi.Models.ForecastLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TemperatureC")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("City", "RequestedAt");

                    b.ToTable("ForecastLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "London",
                            RequestedAt = new DateTime(2024, 3, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Mild with occasional clouds",
                            TemperatureC = 18.5f
                        },
                        new
                        {
                            Id = 2,
                            City = "London",
                            RequestedAt = new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Sunny with light breeze",
                            TemperatureC = 19.2f
                        });
                });

            modelBuilder.Entity("AdvancedWebApi.Models.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Pressure")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WindDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Location", "Timestamp");

                    b.ToTable("WeatherRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Conditions = "Partly Cloudy",
                            Humidity = 65.0,
                            Location = "London",
                            Pressure = 1013.2,
                            Temperature = 18.5,
                            Timestamp = new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            WindDirection = "NW",
                            WindSpeed = 12.300000000000001
                        },
                        new
                        {
                            Id = 2,
                            Conditions = "Sunny",
                            Humidity = 62.0,
                            Location = "London",
                            Pressure = 1012.8,
                            Temperature = 19.199999999999999,
                            Timestamp = new DateTime(2024, 3, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            WindDirection = "NW",
                            WindSpeed = 11.800000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
