name: Deploy to Fly.io

on:
  push:
    branches: [ dev, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build and Test WeatherCrud
      run: |
        dotnet build Level2/Level2.WeatherCrud/Level2.WeatherCrud.csproj --configuration Release
        dotnet test Level2/Level2.WeatherCrud.Tests/Level2.WeatherCrud.Tests.csproj --configuration Release

    - name: Install Flyctl
      run: |
        curl -L https://fly.io/install.sh | sh
        echo "FLYCTL_INSTALL=$HOME/.fly" >> $GITHUB_ENV
        echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV

    - name: Set Database URL Secret
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl secrets set DATABASE_URL="${{ secrets.DATABASE_URL }}" --config Level2/fly.toml

    - name: Deploy to Fly
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl deploy --config Level2/fly.toml --remote-only 